### ISSUE TITLE
Bug. The numbering isn't always the end is added

### ISSUE THREAD

**Issue by Daruse93** [wcoder/highlightjs-line-numbers.js#13]
The numbering isn't always the end is added
http://prntscr.com/djavbu

[Link article](http://daruse.ru/sozdanie-dopolnitelnyix-polej-tv-cherez-xpdo-v-modx-revolution)

Please tell me the solution

**Comment by vafrcor** [comment]
I have this issue to. Any solution?
preview: ![highlight-line-number-issue](https://cloud.githubusercontent.com/assets/2148366/23005763/87d966ee-f430-11e6-94ab-4f2246fa85da.png)

**Comment by lerminou** [comment]
This is due to soft-wraps, but for now, I do not have solutions that work all the time

**Comment by lerminou** [comment]
@wcoder , please have a look at my pull request, for me this bug id resolved.
