### ISSUE TITLE
v2.0 uses innerHTML, which removes nodes referenced in other code

### ISSUE THREAD

**Issue by jamespatterson** [wcoder/highlightjs-line-numbers.js#17]
I am trying to use this extension with highlightjs inside a ckeditor widget. The line numbering is added fine, but when ckeditor switches to source mode or attempts to save, it crashes. Without this extension, highlightjs works fine with ckeditor. I think it's because v2 uses innerHTML instead of DOM methods, and therefore nodes ckeditor expects to find are rewritten after they are already referenced.

Any chance v2 could be improved to use DOM methods like v1.1 did?

**Comment by wcoder** [comment]
@jamespatterson, thanks for using the plugin and for your question!

Currently used new layout for numbers panel, so `innerHTML` remain in future.

I can advise solutions:

- use v1.1
- customize v2.0 for your cases
- reinitialize ckeditor after switching

**Comment by tm-tomers** [comment]
I ran into the a similar issue and using v1.1 instead of v2.x solved the problem, thanks @wcoder!
