### ISSUE TITLE
No numbers when there is only one line

### ISSUE THREAD

**Issue by rolandtoth** [wcoder/highlightjs-line-numbers.js#18]
There is no line numbers when there is only one line available. Could there be a setting to add it even in such case? Or at least add a class to the dom node so one can style the node accordingly (currently there is no way to distinguish ones with numbering).

**Comment by wcoder** [comment]
@rolandtoth, thanks for your question!
Now it is available via the options. Look at version 2.1
https://github.com/wcoder/highlightjs-line-numbers.js#examples-of-using

**Comment by rolandtoth** [comment]
Thanks! Will try soon and report back.

**Comment by rolandtoth** [comment]
Works great  here, thanks again!
