### ISSUE TITLE
Syntax highlighting not work for multiline comments in Javascript

### ISSUE THREAD

**Issue by gungweb** [wcoder/highlightjs-line-numbers.js#26]
syntax highlighting only work on first comment.

**Comment by wcoder** [comment]
Hi @gungweb thanks for the feedback!

Duplicated #21 

Please, try the solution from the separate branch:

https://github.com/wcoder/highlightjs-line-numbers.js/blob/bugfixes/multiline-nodes/src/highlightjs-line-numbers.js
