### ISSUE TITLE
It seems to destroy some of the structure.

### ISSUE THREAD

**Issue by nasyxx** [wcoder/highlightjs-line-numbers.js#29]
Before:
<img width="442" alt="screen shot 2018-02-06 at 8 07 02 pm" src="https://user-images.githubusercontent.com/5007613/35859046-9225ce38-0b79-11e8-9086-5ed6c65ded19.png">
<img width="457" alt="screen shot 2018-02-06 at 8 07 25 pm" src="https://user-images.githubusercontent.com/5007613/35859052-95a7fc8e-0b79-11e8-93e2-25b488661810.png">
After:
<img width="466" alt="screen shot 2018-02-06 at 8 08 32 pm" src="https://user-images.githubusercontent.com/5007613/35859060-9c008d62-0b79-11e8-97a4-1ab43250fdbf.png">
<img width="494" alt="screen shot 2018-02-06 at 8 08 40 pm" src="https://user-images.githubusercontent.com/5007613/35859064-9f81b574-0b79-11e8-952f-70357d62f3da.png">

Is there any way to avoid this happening?

**Comment by wcoder** [comment]
Hi @nasyxx, thanks for the feedback.

This is a known issue in the latest version of the plugin.

I tried to fix it in dev branch, please try it, should help you:

https://github.com/wcoder/highlightjs-line-numbers.js/blob/bugfixes/multiline-nodes/src/highlightjs-line-numbers.js
