### ISSUE TITLE
Removing phpDoc comments

### ISSUE THREAD

**Issue by lex111** [wcoder/highlightjs-line-numbers.js#32]
Before
![image](https://user-images.githubusercontent.com/4408379/36982663-6dd13904-20a1-11e8-8e81-bba226c5e27f.png)

After
![image](https://user-images.githubusercontent.com/4408379/36982585-41ee10b4-20a1-11e8-902e-1cb701e81f9f.png)

Version 2.2.0

**Comment by lex111** [comment]
А на версии 2.1 комментарии не удаляются, но изначальная подсветка работает только для первой строки

![image](https://user-images.githubusercontent.com/4408379/36982965-3ba1bf70-20a2-11e8-91a9-f35001e458d5.png)

**Comment by wcoder** [comment]
Thanks for the feedback!

I will check this bug today.

P.S. Можете скинуть пример в текстовом виде, для ускорения воспроизведения?

**Comment by lex111** [comment]
Вот полный файл, кстати заметил сейчас ещё одну проблему - при копировании в начало каждой строки вставляется вертикальная строка (|), при отключенном номерах строк такого нет.

```php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity
 */
class Post
{
    const NUM_ITEMS = 10;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="string")
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string")
     */
    private $authorEmail;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @ORM\OneToMany(
     *      targetEntity="Comment",
     *      mappedBy="post",
     *      orphanRemoval=true
     * )
     * @ORM\OrderBy({"publishedAt"="ASC"})
     */
    private $comments;

    public function __construct()
    {
        $this->publishedAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    // getters and setters ...
}

```

**Comment by lex111** [comment]
@wcoder приветствую, как дела с этим багом? Куда копать для его исправления?

**Comment by wcoder** [comment]
Здравствуйте, @lex111

Исправление уже сейчас можно попробовать здесь: https://raw.githubusercontent.com/wcoder/highlightjs-line-numbers.js/bugfixes/phpdoc/dist/highlightjs-line-numbers.min.js

В ближайшее время собираюсь выпустить обновление.

**Comment by lex111** [comment]
@wcoder проверил, работает отлично, спасибо 👍

**Comment by lex111** [comment]
Хотя есть небольшой баг, добавляется лишняя пустая строка, см скриншоты ниже:

До включения плагина
![image](https://user-images.githubusercontent.com/4408379/37391740-2ffb7332-277d-11e8-99b5-2f46e628fe87.png)

После включения:

![image](https://user-images.githubusercontent.com/4408379/37391764-3ec0cf48-277d-11e8-9068-563492a1a90c.png)

Может, из-за стилей подобное?

**Comment by wcoder** [comment]
@lex111 

исправленный вариант:

https://raw.githubusercontent.com/wcoder/highlightjs-line-numbers.js/dev/dist/highlightjs-line-numbers.min.js

**Comment by lex111** [comment]
@wcoder круто, спасибо, скоро релиз?

**Comment by lex111** [comment]
@wcoder а можно еще одно улучшение, хотя оно не связанно с этим багом. В общем, можно проставлять класс для тега `code`, если нумерация строк кода включена, просто если блок кода состоит из одной строки, то нумерации строк нет, как раз чтобы отслеживать такую ситуацию нужен класс (в моем случае по умолчанию `padding` равен нулю, предполагая, что блок кода состоит из нескольких строк, соответственно, применяется плагин, и его стили, и если, блок кода состоит из одной строки, нужен небольшой padding), можно подобное сделать?

**Comment by wcoder** [comment]
@lex111, вы можете включить нумерацию строк для одной строки, используя опцию `singleLine`:
https://github.com/wcoder/highlightjs-line-numbers.js#options

**Comment by lex111** [comment]
@wcoder да, но если этого не нужно, а отслеживать нумерацию как-то надо...

**Comment by wcoder** [comment]
@lex111 используйте `singleLine: true` (нумерация будет отслеживаться) + стили (для скрытия нумерации)

**Comment by wcoder** [comment]
@lex111 релиз 2.3 доступен в npm
