### ISSUE TITLE
Wonky css when combined with Bootstrap

### ISSUE THREAD

**Issue by SumNeuron** [wcoder/highlightjs-line-numbers.js#36]
Just tried to use this with Bootstrap and what was nicely highlighted code with `hightlightjs` became a weirdly spaced mess.

Please check css to make compatible with Bootstrap v4

**Comment by wcoder** [comment]
Hi @SumNeuron thank you for feedback!

I tried to use default version of plugin and bootstrap, works fine.

**Note:** This plugin styles full customizable, and you can change each property.

Could you please provide me with an example of messed view?

**Comment by xiaozi0lei** [comment]
@wcoder I think @SumNeuron means

**Comment by wcoder** [comment]
@xiaozi0lei thank you for the detailed answer!

I will close this issue, if anyone has the same problem, please write here.
