### ISSUE TITLE
Using line numbering changes coloring of certain JSON elements to black color

### ISSUE THREAD

**Issue by klische** [wcoder/highlightjs-line-numbers.js#38]
**Describe the bug**
Using the latest version of highlight.js (9.12) and the line numbers library (2.3), certain elements in JSON (curly braces, colons, commas, and brackets) are now in black color. Not using the line numbering library does not produce this effect. It also changes the font size, but that's not too much of a concern for me.

**To Reproduce**
1. Clone the repo here: https://github.com/klische/HighlightJSLineNumbers/tree/master
2. Open the index.html and observe that those elements listed above are in black color

**Expected behavior**
1. Clone the repo here: https://github.com/klische/HighlightJSLineNumbers/tree/master
2. Open the index_no_line_number.html and observe that those elements listed above are in the correct color

**Screenshots**
<img width="388" alt="screen shot 2018-06-03 at 9 39 52 pm" src="https://user-images.githubusercontent.com/29829961/40898706-f896b6fa-6777-11e8-965c-2f4093a9e1c8.png">
<img width="610" alt="screen shot 2018-06-03 at 9 40 25 pm" src="https://user-images.githubusercontent.com/29829961/40898710-ff34a738-6777-11e8-84ee-123b5dc2d92c.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4 (17E202)
 - Browser: Safari Version 11.1 (13605.1.33.1.4) and Chrome Version 67.0.3396.62 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPad Pro 12.9"
 - OS: iOS 11.3
 - Browser: WKWebView
 - Version: iOS 11.3

**Comment by wcoder** [comment]
Hi @klische thank you for the feedback!

Interesting issue, I will think about the better solution.

### Workaround
I propose to set color for `.hljs-ln`, because default styles of table override style-properties of `.hljs`)
```css
.hljs-ln {
    color: #f8f8f2;
}
```

**Comment by klische** [comment]
That works! Unfortunately, the spacing is ignored :( I just noticed that. It shifts everything to the left.

**Comment by wcoder** [comment]
Yes, you are right.

I already created the issue #39 about this.
