### ISSUE TITLE
Multiline html comment bug

### ISSUE THREAD

**Issue by w3suli** [wcoder/highlightjs-line-numbers.js#45]
**Example:**
&lt;!--
&lt;div&gt;...&lt;/div&gt;
&lt;div&gt;...&lt;/div&gt;
--&gt;

highlighted only first comment tag (&lt;!--)!
All modern browser, All OS

**Comment by wcoder** [comment]
@w3suli thanks for the feedback!

This bug was fixed in version 2.3+

Duplicate #32 #35 #46
