### ISSUE TITLE
Thanks for this plug-in

### ISSUE THREAD

**Issue by aligoren** [wcoder/highlightjs-line-numbers.js#5]
Thanks for this plugin. This plugin works fine. 

Below are some screenshots for my php project:

![http://i.hizliresim.com/1MrEAp.png](http://i.hizliresim.com/1MrEAp.png)

![screen shot 2016-01-02 at 14 21 01](https://cloud.githubusercontent.com/assets/4205423/12074434/f528e62e-b15c-11e5-8253-1e8791219136.png)

![screen shot 2016-01-02 at 14 21 19](https://cloud.githubusercontent.com/assets/4205423/12074435/f970c800-b15c-11e5-9f91-918afcb63af7.png)

**Comment by wcoder** [comment]
Thanks for using!
I'll be use your screenshots in main page for demonstrate work plugin.
