### ISSUE TITLE
Start numbering from value other than 1

### ISSUE THREAD

**Issue by peske** [wcoder/highlightjs-line-numbers.js#67]
**Is your feature request related to a problem? Please describe.**
In some cases, I would like to be able to specify that numbering starts from a custom value, other than `1`.

**Describe the solution you'd like**
Ability to specify an _offset_ which should be used for particular `code` block.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peske** [comment]
Again, I've already implemented that. Here's the PR: https://github.com/wcoder/highlightjs-line-numbers.js/pull/65

I'm _put-up-or-shut-up_ kind of guy :)

**Comment by myroslambda** [comment]
@wcoder Do you think this is something that could be included since there is PR already?

**Comment by wcoder** [comment]
@myroslambda done 

Please check v2.8.0

Please reopen if you still questions.
