### ISSUE TITLE
How can you  download the code?

### ISSUE THREAD

**Issue by founshi** [wcoder/highlightjs-line-numbers.js#70]
How can you download the code

**Comment by wcoder** [comment]
You can do it simply via direct links on the latest master:

Sources (`src` folder):
https://github.com/wcoder/highlightjs-line-numbers.js/raw/master/src/highlightjs-line-numbers.js

Minified sources (`dist` folder):
https://raw.githubusercontent.com/wcoder/highlightjs-line-numbers.js/master/dist/highlightjs-line-numbers.min.js

CDN provides:
https://github.com/wcoder/highlightjs-line-numbers.js#getting-the-library-from-cdn
