### ISSUE TITLE
После подключения плагина line-numbers все страницы дергается

### ISSUE THREAD

**Issue by dokxpi** [wcoder/highlightjs-line-numbers.js#8]
Область нумерации существенно опаздывает и тем самым заставляет сайт дёргается (подозреваю, что это из за свойств полосы прокрутки overflow)

https://dokxpi.github.io/knowhow/highlight/highlightjs-line-numbers.html `- highlight+line-numbers`
https://dokxpi.github.io/knowhow/highlight `- чистый highlight`

Странно то, что на вашей демонстрационной страницы такого эффекта нет, страница грузиться плавно и без подергиваний http://wcoder.github.io/highlightjs-line-numbers.js/, но стоит только добавить  https://  и плагин highlight вовсе перестанет работать 

Скажите, это можно как-то исправить?

**Comment by wcoder** [comment]
[Исправил демо](https://github.com/wcoder/highlightjs-line-numbers.js/commit/c60f2c379be755aea05e83a723dc3ae30d7dfaaf), теперь работает и с https - https://wcoder.github.io/highlightjs-line-numbers.js/

Изменил процесс загрузки плагина. Попробуйте последнюю версию тут: https://github.com/wcoder/highlightjs-line-numbers.js/archive/dev.zip 

Если это помогло, включу в основную ветку.

**Comment by dokxpi** [comment]
Помогло. Спасибо большое

**Comment by wcoder** [comment]
Исправление включено в основную ветку.

**Comment by dokxpi** [comment]
@wcoder  чтобы не плодить темы, спрошу здесь

А можно как-то маркером выделять производные части кода или хотя бы строки? Вам не встречались готовые решения для highlightjs.js?
![2016-02-29_190052](https://cloud.githubusercontent.com/assets/10334512/13403017/9e4c124e-df1b-11e5-812a-7e9ed630deeb.png)

ПС. SyntaxHighlighter умеет, только вот подсветка там адова

**Comment by wcoder** [comment]
@dokxpi, спасибо за вопросы!

Текущая реализация подобной возможности не имеет. Но, в этой ветке [feature/line-link](https://github.com/wcoder/highlightjs-line-numbers.js/tree/feature/line-link) реализована возможность ссылаться на конкретную строку (из обсуждения [Relative line links?](https://github.com/wcoder/highlightjs-line-numbers.js/issues/7))

Готовое решение для highlightjs.js не встречал.

Думаю в планах следует реализовать данную возможность.

P.S. хех, нужно было плодить новую тему :smile: чтобы можно было следить за обсуждением фичи и ее реализацией и т.п.

**Comment by dokxpi** [comment]
> Исправление включено в основную ветку.
А для расширенной ветки, там где реализована возможность ссылаться на конкретную строку, исправление будет? 
https://github.com/wcoder/highlightjs-line-numbers.js/archive/feature/line-link.zip
