### ISSUE TITLE
Support version(s) is undocumented

### ISSUE THREAD

**Issue by clach04** [wcoder/highlightjs-line-numbers.js#88]
**Describe the bug**
Readme does not document the known working versions of highlightjs.

Implications of this is that it is not clear that highlight.js 11.3.1 does not work with highlightjs-line-numbers.js 2.6.0

From looking at the demo https://wcoder.github.io/highlightjs-line-numbers.js/ it looks like highlightjs-line-numbers.js 2.6.0 works with highlight.js 8.6

**Additional context**

    hljs.initHighlightingOnLoad();  // Deprecated as of 10.6.0. initHighlightingOnLoad() deprecated.  Use highlightAll()

**Comment by clach04** [comment]
I had a quick play and was able to get current versions as of 2021 to work :)

https://github.com/clach04/highlightjs-line-numbers.js/commit/2563e180a2e48ef0cc147be3e5536d2fcd6bb5f6

highlightjs-line-numbers.js 2.8.0 working with highlight.js 11.3.1

**Comment by wcoder** [comment]
Docs, samples and demo were updated
@clach04 thanks!
