### ISSUE TITLE
highlightjs-line-numbers changes code font

### ISSUE THREAD

**Issue by wermos** [wcoder/highlightjs-line-numbers.js#93]
**Describe the bug**
The `highlightjs-line-numbers` plugin changed the code font on [my Jekyll blog](https://wermos.github.io/blog/jekyll/update/welcome-to-jekyll/) ([repo link](https://github.com/wermos/blog/tree/custom-liquid-tag)) when I added it as a plugin, following the instructions given in the usage portion of the README.

**Expected behavior**
The code font should not change.

**Screenshots**
This is what code snippets currently look like:
![image](https://user-images.githubusercontent.com/63574588/190344534-6cf87624-ed98-4775-af01-b9c11a7fae73.png)

This is what they're supposed to look like, but with line numbers:
![image](https://user-images.githubusercontent.com/63574588/190344713-422b6f15-b3eb-4857-a7c7-6a910b3d9cb7.png)

**Desktop:**
 - OS: Windows
 - Browser: Edge
 - Version: 105.0.1343.33

However, I don't think this is a browser-specific issue.

**Additional context**
In the `main` branch, one can see the [code I added](https://github.com/wermos/blog/blob/2804f3ff03dada85d96af1cff45cebf84fda2a50/_includes/scripts.html#L36-L39) to `_include/scripts.html` to get `highlight.js` working.

In the `custom-liquid-tag` branch, the only lines I changed were [these](https://github.com/wermos/blog/blob/3f24b886e5d9e9a6020648f851b976d2d9a387c8/_includes/scripts.html#L38-L43), in accordance with the README, but the code font inexplicably changed.

**Comment by wcoder** [comment]
Line-number plugin uses table under the hood.

Table styles on your site override and broke font, try to rework:
<img width="322" alt="Screen Shot 2022-09-16 at 12 37 45 AM" src="https://user-images.githubusercontent.com/766193/190513371-a3308fdf-75f6-435d-a5c3-75f039eaeba6.png">

**Comment by wermos** [comment]
Wow, thank you so much! I had been trying to solve this issue for the past 3 days, and now I finally know what was happening. I'll close this issue, because this is not an actual bug with the plugin.
